<?php

########################################################################
# Extension Manager/Repository config file for ext: "hs_questionnaire"
#
# Auto generated by Extension Builder 2012-05-24
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Easy Questionnaire',
	'description' => 'Create questionnaires with ease.',
	'category' => 'module',
	'author' => 'Tim Ruether, Stefan Seehafer, Mike Loose',
	'author_email' => 'info@holosystems.de',
	'author_company' => 'holosystems',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.0',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.3',
			'fluid' => '1.3',
			'typo3' => '4.5',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>